outdir: "/home/william.benoit/aframe/o4b_bbh_model/"
datadir: "/dev/shm/kafka"
aframe_architecture:
  class_path: architectures.supervised.SupervisedTimeDomainResNet
  init_args:
    layers: [3, 4, 6, 3]
    norm_layer:
      class_path: ml4gw.nn.norm.GroupNorm1DGetter
      init_args:
        groups: 16
aframe_weights: /home/william.benoit/aframe/o4b_bbh_model/training/weights.pt
amplfi_architecture: 
  class_path: architectures.supervised.SupervisedTimeDomainResNet
  init_args: 
amplfi_weights: 
ifos: ["H1", "L1"]
channel: "GDS-CALIB_STRAIN"
sample_rate: 2048
kernel_length: 1.5
inference_sampling_rate: 512
psd_length: 64
trigger_distance: -0.75
fduration: 1
integration_window_length: 1
fftlength: null
highpass: 32
refractory_period: 8
far_threshold: 1 
server: "local"
ifo_suffix: 
input_buffer_length: 75
output_buffer_length: 8
verbose: true
